version: "3"
services:
  node:
    container_name: node
    restart: always
    build: .
    command: "node app.js"
    environment:
      - NODE_ENV=development
    volumes:
      - ./library:/home/library
      - /home/library/node_modules
    expose:
      - "5000"
    ports:
      - "5000:5000"
