version: "3"
services:
  node:
    container_name: node
    restart: always
    build: .
    command: "npm start"
    environment:
      - NODE_ENV=development
    volumes:
      - ./library:/home/library
      - /home/library/node_modules
      - /home/library/public/lib

    expose:
      - "3000"
    ports:
      - "3000:3000"
