version: "3"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/library
    environment:
      - NODE_ENV=development
    volumes:
      - ./library:/home/node/library
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "node app.js"
